[package]
name = "advent_of_code_2021"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
ndarray = "0.15.4"
ndarray-stats = "0.5.0"
noisy_float = "0.2.0"
petgraph = "0.6.0"
